Repository MRU-Dev-Circle/ProjectMRU, pull requests merged in 2020-10, with the labels that each got.

#42 Update for hacktobefest
  CONTRIBUTORS.md
  Profiles/Vipul.md
Labels: hacktoberfest-accepted

#43 Create vipul.md
  Profiles/vipul.md
Labels: hacktoberfest-accepted

#44 Create Hello_world_Vipul.cpp
  Scripts/C++/Hello_world_Vipul.cpp
Labels: hacktoberfest-accepted

#45 Create Hello_world_Vipul.cpp
  Scripts/C++/Hello_world_Vipul.cpp
  Scripts/Javascript/Local weather app.js
Labels: hacktoberfest-accepted

#50 Addition : Readme.md,Profiles,Scripts
  CONTRIBUTORS.md
  Profiles/anshvarun.md
  Scripts/Javascript/convertTimeStamp_anshcena.js
Labels: hacktoberfest-accepted

#51 Create bash.sh
  Scripts/Bash/bash.sh
Labels: hacktoberfest-accepted

#52 hacktoberfest
  CONTRIBUTORS.md
  Profiles/c0sz.md
  Scripts/Bash/input.sh
  Scripts/Bash/while.sh
Labels: hacktoberfest-accepted

#53 Create if.sh
  Scripts/Bash/if.sh
Labels: hacktoberfest-accepted

#54 Create ifand.sh
  Scripts/Bash/ifand.sh
Labels: hacktoberfest-accepted

#55 Create else.sh
  Scripts/Bash/else.sh
Labels: hacktoberfest-accepted

#56 Contribution PR to contributors/profiles/scripts
  .idea/.gitignore
  .idea/ProjectMRU.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  CONTRIBUTORS.md
  Profiles/auxfuse.md
  Scripts/Python/hello_world_auxfuse.py
Labels: great work, hacktoberfest-accepted

#57 Add hello-world-antinoni.java
  Scripts/Java/hello-world-antinoni.java
Labels: hacktoberfest-accepted

#58 Create Hello_World.py
  Scripts/Python/Hello_World.py
Labels: hacktoberfest-accepted

#59 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#60 Create hello.py
  Scripts/Python/hello.py
Labels: hacktoberfest-accepted

#65 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#66 Create Helloworld.md
  Profiles/Helloworld.md
Labels: hacktoberfest-accepted

#67 Create a Program to find nature of roots of a quadratic
  Scripts/C++/Roots_c++_Program.CPP
Labels: hacktoberfest-accepted

#68 Add files via upload
  Scripts/Other language/HelloWorld.go
Labels: hacktoberfest-accepted

#77 Sams branch
  CONTRIBUTORS.md
  Profiles/Sam_Laubscher.md
  Scripts/Python/hello_world_sam_l.py
Labels: hacktoberfest-accepted

#78 added guberlo to contributors
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#79 New Profile Added
  CONTRIBUTORS.md
  Profiles/lkmSasanga.md
  Scripts/Python/__pycache__/html.cpython-38.pyc
  Scripts/Python/helloWorld_lkmSasanga.py
Labels: hacktoberfest-accepted

#80 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
  Profiles/superTO.md
  Scripts/Javascript/hello_world_superTO.js
Labels: hacktoberfest-accepted

#81 project c++
  Scripts/C++/project c++
  project c++
Labels: invalid

#76 Optimize way to fibonacci series
  CONTRIBUTORS2.md
  dheeraj-gupta.md
Labels: invalid
