Repository MRU-Dev-Circle/ProjectMRU, pull requests merged in 2021-10, with the labels that each got.

#84 Ready for 2021
  2020/Profiles/AbhishekGupta.md
  2020/Scripts/C/H_Pattern.CPP
Labels: hacktoberfest-accepted

#85 Create Binarysearch.c
  Scripts/C/Binarysearch.c
Labels: hacktoberfest-accepted

#87 Added myprofile, helloworld script and updated contributors
  CONTRIBUTORS.md
  Profiles/imsushant12.md
  Scripts/Python/hello_world_imsushant12.py
Labels: hacktoberfest-accepted, hacktober-fest

#88 next-greater-element.cpp
  2020/Scripts/C++/next_greater_element.cpp
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted, hacktober-fest

#94 added plz approve
  CONTRIBUTORS.md
  Scripts/Python/hactoberhello.py
Labels: hacktoberfest-accepted, hacktober-fest

#95 Java commit
  Profiles/rupalisingh.md
  Scripts/Java/Build Array From Permutation.java
Labels: hacktoberfest-accepted, hacktober-fest, knowledge-purpose

#91 Merge Sort in Python
  CONTRIBUTORS.md
  Scripts/Python/mergSort.py
Labels: hacktoberfest-accepted, hacktober-fest, knowledge-purpose
